app:
  storage:
    path: ${APP_STORAGE_PATH:apps/data}
jwt:
  expiration: ${JWT_EXPIRATION:8640000000}
  secret: ${JWT_SECRET:change-this-secretfdsfas-key-in-produfasdftion-at-least-256-bits}
logging:
  level:
    com:
      metacraft:
        api: DEBUG
server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: metacraft-api
  datasource:
    driver-class-name: ${DB_DRIVER:org.postgresql.Driver}
    password: ${DB_PASSWORD}
    url: ${DB_URL}
    username: ${DB_USERNAME}
  flyway:
    baseline-on-migrate: true
    enabled: true
    locations: classpath:db/migration
    validate-on-migrate: true
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  main:
    banner-mode: 'off'
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    operations-sorter: alpha

langchain4j:
  community:
    dashscope:
      chat-model:
        model-name: ${MODEL_NAME:qwen-plus}
        api-key: ${API_KEY}
      streaming-chat-model:
        model-name: ${MODEL_NAME:qwen-plus}
        api-key: ${API_KEY}
